services:
  php_prebuilt:
    profiles: ["php.prebuilt"]
    hostname: php
    image: webdevops/php-dev:${PHP_VERSION:-8.0}-alpine
    volumes:
      - "${SOURCE_PATH:-../mybb}:/var/www/html"
    environment:
      - PHP_MAX_EXECUTION_TIME=0
      - php.html_errors=1
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_START_WITH_REQUEST=1
  php_custom:
    profiles: ["php.custom"]
    hostname: php
    build:
      context: ./php/8.0
      args:
        - PHP_VERSION=${PHP_VERSION:-8.0}
        - XDEBUG=1
        - XDEBUG_VERSION=${XDEBUG_VERSION:-}
    volumes:
      - "${SOURCE_PATH:-../mybb}:/var/www/html"
      - "./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_HOST=host.docker.internal

  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PUBLISHED_PORT:-8080}:80"
    volumes:
      - "${SOURCE_PATH:-../mybb}:/var/www/html"
      - "./nginx/mybb.conf:/etc/nginx/conf.d/default.conf"

  postgresql:
    profiles: ["db.postgresql"]
    image: postgres
    environment:
      POSTGRES_DB: mybb
      POSTGRES_USER: mybb
      POSTGRES_PASSWORD: mybb
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "${POSTGRESQL_PUBLISHED_PORT:-6432}:5432"
  mysql:
    profiles: ["db.mysql"]
    image: mariadb
    environment:
      MYSQL_USER: mybb
      MYSQL_PASSWORD: mybb
      MYSQL_DATABASE: mybb
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
    - /var/lib/db/data
    ports:
    - "${MYSQL_PUBLISHED_PORT:-4306}:3306"
