services:
  # PHP interpreters & tools
  composer:
    profiles: ["composer"]
    image: composer:latest
    command: /scripts/composer-install.sh
    environment:
      - COMPOSER_NO_DEV=${COMPOSER_NO_DEV:-}
    volumes:
      - "${SOURCE_PATH:-../mybb}:/app"
      - "./scripts:/scripts"

  php:
    extends:
      service: php_${PHP_IMAGE}
      file: docker-compose.partial.yml
    volumes:
      - "${SOURCE_PATH:-../mybb}:/var/www/html"
      - "./xdebug:/var/log/xdebug"
    working_dir: /var/www/html
    environment:
      - PHP_MAX_EXECUTION_TIME=0
      - PHP_DISPLAY_ERRORS=1
      - PHP_HTML_ERRORS=1
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_LOG=/var/log/xdebug/xdebug.log
      - XDEBUG_MODE=debug
      - XDEBUG_FILE_LINK_FORMAT="phpstorm://open?file=%f&line=%l"
      - XDEBUG_OUTPUT_DIR=/var/log/xdebug
      - XDEBUG_START_WITH_REQUEST=1
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG:-}
      - MYBB_DEV_MODE=${MYBB_DEV_MODE:-}
    depends_on:
      composer:
        condition: service_completed_successfully

  install:
    profiles: ["install"]
    extends:
      service: php
    command: /scripts/mybb-install.sh
    environment:
      MYBB_INSTALL_BBURL: http://localhost:${NGINX_PUBLISHED_PORT:-8080}
      MYBB_DEV_MODE: ${MYBB_DEV_MODE:-}
    volumes:
      - "./scripts:/scripts"

  # web servers
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PUBLISHED_PORT:-8080}:80"
    volumes:
      - "${SOURCE_PATH:-../mybb}:/var/www/html"
      - "./nginx/mybb.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      php:
        condition: service_started

  # database systems
  postgresql:
    profiles: ["db.postgresql"]
    image: postgres
    environment:
      POSTGRES_DB: mybb
      POSTGRES_USER: mybb
      POSTGRES_PASSWORD: mybb
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "${POSTGRESQL_PUBLISHED_PORT:-6432}:5432"

  mysql:
    profiles: ["db.mysql"]
    image: mariadb
    environment:
      MYSQL_USER: mybb
      MYSQL_PASSWORD: mybb
      MYSQL_DATABASE: mybb
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
    - /var/lib/db/data
    ports:
    - "${MYSQL_PUBLISHED_PORT:-4306}:3306"
