services:
  php:
    build:
      context: ./php/8.0
      args:
        - XDEBUG=1
    volumes:
      - "${SOURCE_PATH:-../mybb}:/var/www/html"
      - "./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PUBLISHED_PORT:-8080}:80"
    volumes:
      - "${SOURCE_PATH:-../mybb}:/var/www/html"
      - "./nginx/mybb.conf:/etc/nginx/conf.d/default.conf"
  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: mybb
      POSTGRES_USER: mybb
      POSTGRES_PASSWORD: mybb
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "${POSTGRESQL_PUBLISHED_PORT:-6432}:5432"
#  mysql:
#    image: mariadb
#    environment:
#      MYSQL_USER: mybb
#      MYSQL_PASSWORD: mybb
#      MYSQL_DATABASE: mybb
#      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
#    volumes:
#    - /var/lib/db/data
#    ports:
#    - "${MYSQL_PUBLISHED_PORT:-4432}:3306"
